"""Mock molecule records for the MolGenix prototype."""

MOCK_MOLECULES: list[dict[str, str | int | float | bool]] = [
    {
        "target_key": "egfr",
        "name": "MGX-EGFR-001",
        "smiles": "COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1",
        "molecular_weight": 446.9,
        "logp": 3.4,
        "h_bond_donors": 1,
        "h_bond_acceptors": 7,
        "tpsa": 72.8,
        "rotatable_bonds": 8,
        "bioavailability_score": 0.55,
        "solubility_log_s": -4.2,
        "clearance_ml_min_kg": 8.4,
        "half_life_hours": 5.6,
        "herg_risk": "medium",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 620.0,
        "docking_score": -9.4,
        "synthetic_accessibility": 3.1,
        "is_toxic": False,
        "notes": "Balanced kinase-like profile with moderate hERG watch item.",
    },
    {
        "target_key": "egfr",
        "name": "MGX-EGFR-002",
        "smiles": "CCOc1cc2ncnc(Nc3ccc(OC)c(Br)c3)c2cc1N1CCN(C)CC1",
        "molecular_weight": 481.4,
        "logp": 4.1,
        "h_bond_donors": 1,
        "h_bond_acceptors": 7,
        "tpsa": 68.2,
        "rotatable_bonds": 7,
        "bioavailability_score": 0.53,
        "solubility_log_s": -4.8,
        "clearance_ml_min_kg": 11.7,
        "half_life_hours": 3.4,
        "herg_risk": "high",
        "ames_toxicity": False,
        "hepatotoxicity": True,
        "ld50_mg_kg": 180.0,
        "docking_score": -8.8,
        "synthetic_accessibility": 3.8,
        "is_toxic": True,
        "notes": "Strong binder but intentionally flagged for liver safety risk.",
    },
    {
        "target_key": "egfr",
        "name": "MGX-EGFR-003",
        "smiles": "CN1CCN(c2ccc(Nc3ncnc4cc(OCCF)c(OC)cc34)cc2)CC1",
        "molecular_weight": 413.5,
        "logp": 2.9,
        "h_bond_donors": 1,
        "h_bond_acceptors": 8,
        "tpsa": 79.4,
        "rotatable_bonds": 6,
        "bioavailability_score": 0.62,
        "solubility_log_s": -3.6,
        "clearance_ml_min_kg": 9.5,
        "half_life_hours": 6.8,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 840.0,
        "docking_score": -8.5,
        "synthetic_accessibility": 3.4,
        "is_toxic": False,
        "notes": "Improved polarity and solubility in simulated ADMET panel.",
    },
    {
        "target_key": "egfr",
        "name": "MGX-EGFR-004",
        "smiles": "COc1cc2c(Nc3ccc(C#N)cc3)ncnc2cc1OCCN(C)C",
        "molecular_weight": 390.4,
        "logp": 3.0,
        "h_bond_donors": 1,
        "h_bond_acceptors": 7,
        "tpsa": 82.6,
        "rotatable_bonds": 6,
        "bioavailability_score": 0.57,
        "solubility_log_s": -3.9,
        "clearance_ml_min_kg": 7.8,
        "half_life_hours": 7.2,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 760.0,
        "docking_score": -8.1,
        "synthetic_accessibility": 2.9,
        "is_toxic": False,
        "notes": "Nitrile hinge-binder analog with acceptable simulated safety.",
    },
    {
        "target_key": "egfr",
        "name": "MGX-EGFR-005",
        "smiles": "CCN(CC)CCOc1cc2ncnc(Nc3cccc(Cl)c3)c2cc1OC",
        "molecular_weight": 427.9,
        "logp": 4.5,
        "h_bond_donors": 1,
        "h_bond_acceptors": 6,
        "tpsa": 61.8,
        "rotatable_bonds": 9,
        "bioavailability_score": 0.48,
        "solubility_log_s": -5.1,
        "clearance_ml_min_kg": 15.9,
        "half_life_hours": 2.6,
        "herg_risk": "high",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 250.0,
        "docking_score": -7.9,
        "synthetic_accessibility": 3.5,
        "is_toxic": True,
        "notes": "Intentionally toxic cationic analog with hERG liability.",
    },
    {
        "target_key": "egfr",
        "name": "MGX-EGFR-006",
        "smiles": "COc1cc2ncnc(Nc3ccc(C(F)(F)F)cc3)c2cc1OCCO",
        "molecular_weight": 407.4,
        "logp": 3.7,
        "h_bond_donors": 2,
        "h_bond_acceptors": 6,
        "tpsa": 78.0,
        "rotatable_bonds": 6,
        "bioavailability_score": 0.55,
        "solubility_log_s": -4.0,
        "clearance_ml_min_kg": 10.3,
        "half_life_hours": 4.8,
        "herg_risk": "medium",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 590.0,
        "docking_score": -8.3,
        "synthetic_accessibility": 3.2,
        "is_toxic": False,
        "notes": "Trifluoromethyl analog with moderate clearance.",
    },
    {
        "target_key": "egfr",
        "name": "MGX-EGFR-007",
        "smiles": "COc1cc2ncnc(Nc3ccc(F)cc3)c2cc1OCCN1CCCC1",
        "molecular_weight": 397.5,
        "logp": 3.6,
        "h_bond_donors": 1,
        "h_bond_acceptors": 6,
        "tpsa": 63.4,
        "rotatable_bonds": 6,
        "bioavailability_score": 0.58,
        "solubility_log_s": -4.3,
        "clearance_ml_min_kg": 8.9,
        "half_life_hours": 5.1,
        "herg_risk": "medium",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 540.0,
        "docking_score": -7.6,
        "synthetic_accessibility": 2.8,
        "is_toxic": False,
        "notes": "Compact morpholine replacement series member.",
    },
    {
        "target_key": "egfr",
        "name": "MGX-EGFR-008",
        "smiles": "CN(C)CCOc1cc2ncnc(Nc3ccc(N(=O)=O)cc3)c2cc1OC",
        "molecular_weight": 408.4,
        "logp": 3.2,
        "h_bond_donors": 1,
        "h_bond_acceptors": 8,
        "tpsa": 106.3,
        "rotatable_bonds": 7,
        "bioavailability_score": 0.42,
        "solubility_log_s": -4.7,
        "clearance_ml_min_kg": 18.2,
        "half_life_hours": 1.9,
        "herg_risk": "medium",
        "ames_toxicity": True,
        "hepatotoxicity": True,
        "ld50_mg_kg": 95.0,
        "docking_score": -8.0,
        "synthetic_accessibility": 3.6,
        "is_toxic": True,
        "notes": "Nitroaryl analog intentionally included as genotoxic example.",
    },
    {
        "target_key": "jak2",
        "name": "MGX-JAK2-001",
        "smiles": "CC1CN(C2CCN(Cc3ccc(NC(=O)c4ccncc4)cc3)CC2)CCN1C",
        "molecular_weight": 420.6,
        "logp": 2.8,
        "h_bond_donors": 1,
        "h_bond_acceptors": 6,
        "tpsa": 68.7,
        "rotatable_bonds": 6,
        "bioavailability_score": 0.61,
        "solubility_log_s": -3.5,
        "clearance_ml_min_kg": 12.2,
        "half_life_hours": 4.9,
        "herg_risk": "medium",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 690.0,
        "docking_score": -9.1,
        "synthetic_accessibility": 3.7,
        "is_toxic": False,
        "notes": "Piperazine-rich JAK chemotype with simulated kinase affinity.",
    },
    {
        "target_key": "jak2",
        "name": "MGX-JAK2-002",
        "smiles": "Cc1n[nH]c2ncc(Nc3ccc(OCCN4CCCCC4)cc3)nc12",
        "molecular_weight": 365.5,
        "logp": 3.1,
        "h_bond_donors": 2,
        "h_bond_acceptors": 6,
        "tpsa": 78.5,
        "rotatable_bonds": 5,
        "bioavailability_score": 0.59,
        "solubility_log_s": -3.7,
        "clearance_ml_min_kg": 10.8,
        "half_life_hours": 5.4,
        "herg_risk": "medium",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 720.0,
        "docking_score": -8.7,
        "synthetic_accessibility": 3.3,
        "is_toxic": False,
        "notes": "Pyrazolopyrimidine-like analog with good ligand efficiency.",
    },
    {
        "target_key": "jak2",
        "name": "MGX-JAK2-003",
        "smiles": "COc1ccc(Nc2ncc3cc(C(=O)N4CCOCC4)n(C)c3n2)cc1",
        "molecular_weight": 394.4,
        "logp": 2.5,
        "h_bond_donors": 1,
        "h_bond_acceptors": 8,
        "tpsa": 88.6,
        "rotatable_bonds": 5,
        "bioavailability_score": 0.56,
        "solubility_log_s": -3.2,
        "clearance_ml_min_kg": 9.1,
        "half_life_hours": 6.3,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 810.0,
        "docking_score": -8.4,
        "synthetic_accessibility": 3.4,
        "is_toxic": False,
        "notes": "Amide-bearing analog with lower simulated hERG risk.",
    },
    {
        "target_key": "jak2",
        "name": "MGX-JAK2-004",
        "smiles": "Clc1ccc(CNc2ncc3n(C)c(CN4CCN(C)CC4)nc3n2)cc1",
        "molecular_weight": 412.9,
        "logp": 3.9,
        "h_bond_donors": 1,
        "h_bond_acceptors": 7,
        "tpsa": 66.2,
        "rotatable_bonds": 6,
        "bioavailability_score": 0.51,
        "solubility_log_s": -4.4,
        "clearance_ml_min_kg": 16.8,
        "half_life_hours": 2.7,
        "herg_risk": "high",
        "ames_toxicity": False,
        "hepatotoxicity": True,
        "ld50_mg_kg": 160.0,
        "docking_score": -8.9,
        "synthetic_accessibility": 3.9,
        "is_toxic": True,
        "notes": "Potent but intentionally hepatotoxic tertiary amine analog.",
    },
    {
        "target_key": "jak2",
        "name": "MGX-JAK2-005",
        "smiles": "CC(C)n1cc(Nc2ncc(C(=O)NC3CC3)cn2)cn1",
        "molecular_weight": 300.4,
        "logp": 1.8,
        "h_bond_donors": 2,
        "h_bond_acceptors": 6,
        "tpsa": 83.1,
        "rotatable_bonds": 4,
        "bioavailability_score": 0.66,
        "solubility_log_s": -2.6,
        "clearance_ml_min_kg": 13.1,
        "half_life_hours": 3.8,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 930.0,
        "docking_score": -7.4,
        "synthetic_accessibility": 2.6,
        "is_toxic": False,
        "notes": "Lower molecular weight fragment-growth candidate.",
    },
    {
        "target_key": "jak2",
        "name": "MGX-JAK2-006",
        "smiles": "COc1cc(Nc2ncc3cc(C#N)n(C)c3n2)ccc1F",
        "molecular_weight": 335.3,
        "logp": 3.0,
        "h_bond_donors": 1,
        "h_bond_acceptors": 6,
        "tpsa": 75.9,
        "rotatable_bonds": 3,
        "bioavailability_score": 0.60,
        "solubility_log_s": -3.6,
        "clearance_ml_min_kg": 7.7,
        "half_life_hours": 7.1,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 880.0,
        "docking_score": -8.0,
        "synthetic_accessibility": 2.9,
        "is_toxic": False,
        "notes": "Fluoro nitrile analog with durable simulated exposure.",
    },
    {
        "target_key": "jak2",
        "name": "MGX-JAK2-007",
        "smiles": "N#Cc1ccc(Nc2ncc3cc(N4CCOCC4)n(C)c3n2)cc1",
        "molecular_weight": 360.4,
        "logp": 2.7,
        "h_bond_donors": 1,
        "h_bond_acceptors": 8,
        "tpsa": 87.0,
        "rotatable_bonds": 4,
        "bioavailability_score": 0.57,
        "solubility_log_s": -3.4,
        "clearance_ml_min_kg": 10.6,
        "half_life_hours": 5.8,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 770.0,
        "docking_score": -7.8,
        "synthetic_accessibility": 3.2,
        "is_toxic": False,
        "notes": "Cyanophenyl analog with clean simulated Ames call.",
    },
    {
        "target_key": "jak2",
        "name": "MGX-JAK2-008",
        "smiles": "O=N(=O)c1ccc(Nc2ncc3cc(N4CCNCC4)n(C)c3n2)cc1",
        "molecular_weight": 385.4,
        "logp": 2.4,
        "h_bond_donors": 2,
        "h_bond_acceptors": 9,
        "tpsa": 113.5,
        "rotatable_bonds": 4,
        "bioavailability_score": 0.39,
        "solubility_log_s": -4.1,
        "clearance_ml_min_kg": 19.4,
        "half_life_hours": 1.6,
        "herg_risk": "medium",
        "ames_toxicity": True,
        "hepatotoxicity": True,
        "ld50_mg_kg": 80.0,
        "docking_score": -8.2,
        "synthetic_accessibility": 3.5,
        "is_toxic": True,
        "notes": "Nitro-containing analog intentionally flagged toxic.",
    },
    {
        "target_key": "bace1",
        "name": "MGX-BACE1-001",
        "smiles": "CC(C)(C)OC(=O)N[C@@H](Cc1ccccc1)C(O)CN1CCN(Cc2ccccc2)CC1",
        "molecular_weight": 481.6,
        "logp": 3.8,
        "h_bond_donors": 2,
        "h_bond_acceptors": 5,
        "tpsa": 73.4,
        "rotatable_bonds": 10,
        "bioavailability_score": 0.46,
        "solubility_log_s": -4.9,
        "clearance_ml_min_kg": 6.8,
        "half_life_hours": 8.4,
        "herg_risk": "medium",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 610.0,
        "docking_score": -9.0,
        "synthetic_accessibility": 4.5,
        "is_toxic": False,
        "notes": "Hydroxyethylamine-like simulated protease inhibitor.",
    },
    {
        "target_key": "bace1",
        "name": "MGX-BACE1-002",
        "smiles": "COc1ccc(CN2CCN(C[C@H](O)[C@H](NC(=O)C3CC3)c3ccccc3)CC2)cc1",
        "molecular_weight": 439.6,
        "logp": 3.2,
        "h_bond_donors": 2,
        "h_bond_acceptors": 5,
        "tpsa": 65.9,
        "rotatable_bonds": 9,
        "bioavailability_score": 0.50,
        "solubility_log_s": -4.0,
        "clearance_ml_min_kg": 8.2,
        "half_life_hours": 6.9,
        "herg_risk": "medium",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 700.0,
        "docking_score": -8.6,
        "synthetic_accessibility": 4.1,
        "is_toxic": False,
        "notes": "Reduced lipophilicity analog for simulated CNS optimization.",
    },
    {
        "target_key": "bace1",
        "name": "MGX-BACE1-003",
        "smiles": "CCOc1ccccc1CN(CCO)C[C@H](O)[C@H](NC(=O)c1cccnc1)c1ccccc1",
        "molecular_weight": 433.5,
        "logp": 3.0,
        "h_bond_donors": 3,
        "h_bond_acceptors": 6,
        "tpsa": 89.1,
        "rotatable_bonds": 11,
        "bioavailability_score": 0.48,
        "solubility_log_s": -3.8,
        "clearance_ml_min_kg": 11.5,
        "half_life_hours": 4.7,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 780.0,
        "docking_score": -8.1,
        "synthetic_accessibility": 4.2,
        "is_toxic": False,
        "notes": "Polar analog with lower simulated hERG interaction.",
    },
    {
        "target_key": "bace1",
        "name": "MGX-BACE1-004",
        "smiles": "CC(C)c1ccc(CN(CCN(C)C)C[C@H](O)[C@H](NC(=O)OC(C)(C)C)c2ccccc2)cc1",
        "molecular_weight": 510.7,
        "logp": 5.1,
        "h_bond_donors": 2,
        "h_bond_acceptors": 5,
        "tpsa": 70.2,
        "rotatable_bonds": 12,
        "bioavailability_score": 0.37,
        "solubility_log_s": -5.8,
        "clearance_ml_min_kg": 17.6,
        "half_life_hours": 2.4,
        "herg_risk": "high",
        "ames_toxicity": False,
        "hepatotoxicity": True,
        "ld50_mg_kg": 140.0,
        "docking_score": -8.9,
        "synthetic_accessibility": 4.8,
        "is_toxic": True,
        "notes": "Highly lipophilic analog intentionally marked toxic.",
    },
    {
        "target_key": "bace1",
        "name": "MGX-BACE1-005",
        "smiles": "CC1(C)CC(NC(=O)c2cccnc2)C(O)CN(CC2CCOCC2)c2ccccc2O1",
        "molecular_weight": 441.5,
        "logp": 2.6,
        "h_bond_donors": 2,
        "h_bond_acceptors": 7,
        "tpsa": 87.6,
        "rotatable_bonds": 6,
        "bioavailability_score": 0.54,
        "solubility_log_s": -3.4,
        "clearance_ml_min_kg": 9.9,
        "half_life_hours": 5.9,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 860.0,
        "docking_score": -7.9,
        "synthetic_accessibility": 4.0,
        "is_toxic": False,
        "notes": "Conformationally constrained analog with improved solubility.",
    },
    {
        "target_key": "bace1",
        "name": "MGX-BACE1-006",
        "smiles": "NC(=O)c1ccccc1N[C@H](C(O)CN2CCOCC2)c1ccc(F)cc1",
        "molecular_weight": 359.4,
        "logp": 1.9,
        "h_bond_donors": 3,
        "h_bond_acceptors": 5,
        "tpsa": 95.7,
        "rotatable_bonds": 6,
        "bioavailability_score": 0.59,
        "solubility_log_s": -2.7,
        "clearance_ml_min_kg": 14.7,
        "half_life_hours": 3.5,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 920.0,
        "docking_score": -7.2,
        "synthetic_accessibility": 3.5,
        "is_toxic": False,
        "notes": "Smaller polar analog with weaker docking but better ADMET.",
    },
    {
        "target_key": "bace1",
        "name": "MGX-BACE1-007",
        "smiles": "COc1ccc(CN(CC2CC2)C[C@H](O)[C@H](NC(=O)c2ccccc2F)c2ccccc2)cc1",
        "molecular_weight": 458.6,
        "logp": 4.3,
        "h_bond_donors": 2,
        "h_bond_acceptors": 4,
        "tpsa": 58.9,
        "rotatable_bonds": 9,
        "bioavailability_score": 0.45,
        "solubility_log_s": -4.7,
        "clearance_ml_min_kg": 7.3,
        "half_life_hours": 7.8,
        "herg_risk": "medium",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 560.0,
        "docking_score": -8.0,
        "synthetic_accessibility": 4.3,
        "is_toxic": False,
        "notes": "Cyclopropyl amine analog with exposure advantage.",
    },
    {
        "target_key": "bace1",
        "name": "MGX-BACE1-008",
        "smiles": "O=N(=O)c1ccc(CN(CCN(C)C)C[C@H](O)[C@H](NC(=O)c2ccccc2)c2ccccc2)cc1",
        "molecular_weight": 508.6,
        "logp": 4.8,
        "h_bond_donors": 2,
        "h_bond_acceptors": 7,
        "tpsa": 111.4,
        "rotatable_bonds": 11,
        "bioavailability_score": 0.31,
        "solubility_log_s": -5.6,
        "clearance_ml_min_kg": 20.5,
        "half_life_hours": 1.5,
        "herg_risk": "high",
        "ames_toxicity": True,
        "hepatotoxicity": True,
        "ld50_mg_kg": 70.0,
        "docking_score": -8.4,
        "synthetic_accessibility": 4.9,
        "is_toxic": True,
        "notes": "Nitroaryl CNS-inappropriate analog intentionally toxic.",
    },
    {
        "target_key": "tnf",
        "name": "MGX-TNF-001",
        "smiles": "CCOc1ccc(C(=O)Nc2ccc(S(=O)(=O)N3CCOCC3)cc2)cc1",
        "molecular_weight": 404.5,
        "logp": 2.7,
        "h_bond_donors": 1,
        "h_bond_acceptors": 7,
        "tpsa": 89.6,
        "rotatable_bonds": 6,
        "bioavailability_score": 0.57,
        "solubility_log_s": -3.3,
        "clearance_ml_min_kg": 8.6,
        "half_life_hours": 6.2,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 810.0,
        "docking_score": -7.8,
        "synthetic_accessibility": 2.9,
        "is_toxic": False,
        "notes": "Sulfonamide inflammation chemotype with clean profile.",
    },
    {
        "target_key": "tnf",
        "name": "MGX-TNF-002",
        "smiles": "COc1cc(C(=O)Nc2ccc(C(F)(F)F)cc2)ccc1S(=O)(=O)N1CCCC1",
        "molecular_weight": 452.5,
        "logp": 4.0,
        "h_bond_donors": 1,
        "h_bond_acceptors": 6,
        "tpsa": 80.8,
        "rotatable_bonds": 6,
        "bioavailability_score": 0.49,
        "solubility_log_s": -4.6,
        "clearance_ml_min_kg": 13.8,
        "half_life_hours": 3.7,
        "herg_risk": "medium",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 530.0,
        "docking_score": -8.3,
        "synthetic_accessibility": 3.4,
        "is_toxic": False,
        "notes": "Trifluoromethyl analog with stronger simulated binding.",
    },
    {
        "target_key": "tnf",
        "name": "MGX-TNF-003",
        "smiles": "CCN(CC)S(=O)(=O)c1ccc(NC(=O)c2ccco2)cc1",
        "molecular_weight": 332.4,
        "logp": 2.2,
        "h_bond_donors": 1,
        "h_bond_acceptors": 6,
        "tpsa": 84.9,
        "rotatable_bonds": 6,
        "bioavailability_score": 0.64,
        "solubility_log_s": -2.8,
        "clearance_ml_min_kg": 11.2,
        "half_life_hours": 4.9,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 900.0,
        "docking_score": -7.2,
        "synthetic_accessibility": 2.4,
        "is_toxic": False,
        "notes": "Lower-weight sulfonamide with favorable simulated solubility.",
    },
    {
        "target_key": "tnf",
        "name": "MGX-TNF-004",
        "smiles": "Clc1ccc(NC(=O)c2ccc(S(=O)(=O)N3CCN(C)CC3)cc2)cc1",
        "molecular_weight": 429.9,
        "logp": 3.5,
        "h_bond_donors": 1,
        "h_bond_acceptors": 6,
        "tpsa": 82.1,
        "rotatable_bonds": 5,
        "bioavailability_score": 0.52,
        "solubility_log_s": -4.1,
        "clearance_ml_min_kg": 15.6,
        "half_life_hours": 2.8,
        "herg_risk": "high",
        "ames_toxicity": False,
        "hepatotoxicity": True,
        "ld50_mg_kg": 150.0,
        "docking_score": -8.0,
        "synthetic_accessibility": 3.2,
        "is_toxic": True,
        "notes": "Basic piperazine analog intentionally carrying hERG and liver risk.",
    },
    {
        "target_key": "tnf",
        "name": "MGX-TNF-005",
        "smiles": "O=C(Nc1ccc(OCCO)cc1)c1ccc(S(=O)(=O)N2CCOCC2)cc1",
        "molecular_weight": 420.5,
        "logp": 2.1,
        "h_bond_donors": 2,
        "h_bond_acceptors": 8,
        "tpsa": 109.9,
        "rotatable_bonds": 8,
        "bioavailability_score": 0.55,
        "solubility_log_s": -2.9,
        "clearance_ml_min_kg": 12.9,
        "half_life_hours": 4.4,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 870.0,
        "docking_score": -7.5,
        "synthetic_accessibility": 3.1,
        "is_toxic": False,
        "notes": "Solubilized analog with acceptable simulated safety.",
    },
    {
        "target_key": "tnf",
        "name": "MGX-TNF-006",
        "smiles": "COc1ccc(NC(=O)c2ccc(S(=O)(=O)NC3CC3)cc2F)cc1",
        "molecular_weight": 390.4,
        "logp": 2.9,
        "h_bond_donors": 2,
        "h_bond_acceptors": 5,
        "tpsa": 84.6,
        "rotatable_bonds": 5,
        "bioavailability_score": 0.60,
        "solubility_log_s": -3.5,
        "clearance_ml_min_kg": 9.4,
        "half_life_hours": 6.0,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 760.0,
        "docking_score": -7.7,
        "synthetic_accessibility": 2.7,
        "is_toxic": False,
        "notes": "Fluoro sulfonamide with steady simulated clearance.",
    },
    {
        "target_key": "tnf",
        "name": "MGX-TNF-007",
        "smiles": "CC(C)c1ccc(NC(=O)c2ccc(S(=O)(=O)N(C)C)cc2)cc1",
        "molecular_weight": 346.4,
        "logp": 3.6,
        "h_bond_donors": 1,
        "h_bond_acceptors": 4,
        "tpsa": 66.4,
        "rotatable_bonds": 5,
        "bioavailability_score": 0.58,
        "solubility_log_s": -3.9,
        "clearance_ml_min_kg": 10.1,
        "half_life_hours": 5.2,
        "herg_risk": "medium",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 640.0,
        "docking_score": -7.1,
        "synthetic_accessibility": 2.5,
        "is_toxic": False,
        "notes": "Simple dimethyl sulfonamide backup compound.",
    },
    {
        "target_key": "tnf",
        "name": "MGX-TNF-008",
        "smiles": "O=N(=O)c1ccc(NC(=O)c2ccc(S(=O)(=O)N3CCOCC3)cc2)cc1",
        "molecular_weight": 421.4,
        "logp": 2.8,
        "h_bond_donors": 1,
        "h_bond_acceptors": 9,
        "tpsa": 126.8,
        "rotatable_bonds": 5,
        "bioavailability_score": 0.36,
        "solubility_log_s": -4.4,
        "clearance_ml_min_kg": 18.6,
        "half_life_hours": 1.8,
        "herg_risk": "medium",
        "ames_toxicity": True,
        "hepatotoxicity": True,
        "ld50_mg_kg": 85.0,
        "docking_score": -7.9,
        "synthetic_accessibility": 3.0,
        "is_toxic": True,
        "notes": "Nitroaryl anti-inflammatory analog intentionally toxic.",
    },
    {
        "target_key": "hiv_integrase",
        "name": "MGX-HIVI-001",
        "smiles": "CCOC(=O)c1c(O)c(C(=O)N2CCOCC2)n(C)c2cc(F)ccc12",
        "molecular_weight": 376.4,
        "logp": 2.1,
        "h_bond_donors": 1,
        "h_bond_acceptors": 8,
        "tpsa": 99.7,
        "rotatable_bonds": 5,
        "bioavailability_score": 0.61,
        "solubility_log_s": -3.0,
        "clearance_ml_min_kg": 7.6,
        "half_life_hours": 8.1,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 940.0,
        "docking_score": -9.2,
        "synthetic_accessibility": 3.2,
        "is_toxic": False,
        "notes": "Diketo-acid-inspired integrase binder with good simulated exposure.",
    },
    {
        "target_key": "hiv_integrase",
        "name": "MGX-HIVI-002",
        "smiles": "O=C(O)c1c(O)c(C(=O)Nc2ccc(F)cc2)n(C)c2ccccc12",
        "molecular_weight": 352.3,
        "logp": 2.8,
        "h_bond_donors": 3,
        "h_bond_acceptors": 6,
        "tpsa": 112.5,
        "rotatable_bonds": 4,
        "bioavailability_score": 0.50,
        "solubility_log_s": -3.7,
        "clearance_ml_min_kg": 9.0,
        "half_life_hours": 6.4,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 790.0,
        "docking_score": -8.8,
        "synthetic_accessibility": 3.1,
        "is_toxic": False,
        "notes": "Acidic chelator analog with strong simulated active-site fit.",
    },
    {
        "target_key": "hiv_integrase",
        "name": "MGX-HIVI-003",
        "smiles": "COc1ccc(NC(=O)c2c(O)c(C(=O)O)n(C)c3ccccc23)cc1F",
        "molecular_weight": 382.3,
        "logp": 2.6,
        "h_bond_donors": 3,
        "h_bond_acceptors": 7,
        "tpsa": 121.7,
        "rotatable_bonds": 5,
        "bioavailability_score": 0.47,
        "solubility_log_s": -3.9,
        "clearance_ml_min_kg": 11.1,
        "half_life_hours": 4.8,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 730.0,
        "docking_score": -8.5,
        "synthetic_accessibility": 3.4,
        "is_toxic": False,
        "notes": "Polar chelator with acceptable simulated tolerability.",
    },
    {
        "target_key": "hiv_integrase",
        "name": "MGX-HIVI-004",
        "smiles": "CCN(CC)CCOc1ccc(NC(=O)c2c(O)c(C(=O)O)n(C)c3ccccc23)cc1",
        "molecular_weight": 451.5,
        "logp": 3.7,
        "h_bond_donors": 3,
        "h_bond_acceptors": 8,
        "tpsa": 119.2,
        "rotatable_bonds": 10,
        "bioavailability_score": 0.42,
        "solubility_log_s": -4.6,
        "clearance_ml_min_kg": 17.2,
        "half_life_hours": 2.3,
        "herg_risk": "high",
        "ames_toxicity": False,
        "hepatotoxicity": True,
        "ld50_mg_kg": 135.0,
        "docking_score": -8.6,
        "synthetic_accessibility": 3.8,
        "is_toxic": True,
        "notes": "Basic side-chain analog intentionally marked toxic.",
    },
    {
        "target_key": "hiv_integrase",
        "name": "MGX-HIVI-005",
        "smiles": "O=C(O)c1c(O)c(C(=O)N2CCN(C3CC3)CC2)n(C)c2cc(F)ccc12",
        "molecular_weight": 399.4,
        "logp": 1.9,
        "h_bond_donors": 2,
        "h_bond_acceptors": 8,
        "tpsa": 112.1,
        "rotatable_bonds": 5,
        "bioavailability_score": 0.55,
        "solubility_log_s": -3.1,
        "clearance_ml_min_kg": 8.8,
        "half_life_hours": 7.0,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 850.0,
        "docking_score": -8.1,
        "synthetic_accessibility": 3.5,
        "is_toxic": False,
        "notes": "Piperazine amide with improved simulated solubility.",
    },
    {
        "target_key": "hiv_integrase",
        "name": "MGX-HIVI-006",
        "smiles": "COC(=O)c1c(O)c(C(=O)Nc2ccc(C#N)cc2)n(C)c2ccccc12",
        "molecular_weight": 361.4,
        "logp": 2.9,
        "h_bond_donors": 2,
        "h_bond_acceptors": 7,
        "tpsa": 111.6,
        "rotatable_bonds": 4,
        "bioavailability_score": 0.52,
        "solubility_log_s": -3.8,
        "clearance_ml_min_kg": 10.4,
        "half_life_hours": 5.6,
        "herg_risk": "medium",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 650.0,
        "docking_score": -7.9,
        "synthetic_accessibility": 3.0,
        "is_toxic": False,
        "notes": "Nitrile phenyl amide with moderate hERG watch item.",
    },
    {
        "target_key": "hiv_integrase",
        "name": "MGX-HIVI-007",
        "smiles": "O=C(O)c1c(O)c(C(=O)NCCO)n(C)c2cc(Cl)ccc12",
        "molecular_weight": 322.7,
        "logp": 1.6,
        "h_bond_donors": 4,
        "h_bond_acceptors": 6,
        "tpsa": 129.9,
        "rotatable_bonds": 5,
        "bioavailability_score": 0.45,
        "solubility_log_s": -2.4,
        "clearance_ml_min_kg": 15.1,
        "half_life_hours": 3.2,
        "herg_risk": "low",
        "ames_toxicity": False,
        "hepatotoxicity": False,
        "ld50_mg_kg": 910.0,
        "docking_score": -7.3,
        "synthetic_accessibility": 2.8,
        "is_toxic": False,
        "notes": "Small polar analog with weaker docking and strong solubility.",
    },
    {
        "target_key": "hiv_integrase",
        "name": "MGX-HIVI-008",
        "smiles": "O=N(=O)c1ccc(NC(=O)c2c(O)c(C(=O)O)n(C)c3ccccc23)cc1",
        "molecular_weight": 393.3,
        "logp": 2.7,
        "h_bond_donors": 3,
        "h_bond_acceptors": 9,
        "tpsa": 154.1,
        "rotatable_bonds": 4,
        "bioavailability_score": 0.34,
        "solubility_log_s": -4.3,
        "clearance_ml_min_kg": 19.8,
        "half_life_hours": 1.7,
        "herg_risk": "medium",
        "ames_toxicity": True,
        "hepatotoxicity": True,
        "ld50_mg_kg": 75.0,
        "docking_score": -8.2,
        "synthetic_accessibility": 3.3,
        "is_toxic": True,
        "notes": "Nitroaryl chelator intentionally included as toxic example.",
    },
]
